# -*- coding: utf-8 -*-

from .common import *

TITLE = '会分期数据库定义'
DEBUG = False
ENABLE_OAUTH = True
OAUTHADMIN_CLIENT_ID = 'ALYqySauCD6as7qrkELo02ZCquIevlJ6fehzIHkW'
OAUTHADMIN_CLIENT_SECRET = 'OXmrzt1H1Oj6AlHGDI99Yky6bBAgNTkTF9uRriCH7wOH9Eo5FChSnEbg86mXJY23QCwVoo5i0Jww8ODyZGMkOOf4zwqEG9Z8NvEHRuMycElVb6NJQub1ipANh9AbUp0X'