# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u5217\u540d', max_length=100)),
                ('data_type', models.CharField(help_text='\u6570\u636e\u7c7b\u578b', max_length=100)),
                ('is_null', models.BooleanField(choices=[(True, 'NULL'), (False, 'NOT NULL')], help_text='\u53ef\u7a7a')),
                ('default_value', models.CharField(blank=True, help_text='\u9ed8\u8ba4\u503c', max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, help_text='\u6ce8\u91ca', max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u6570\u636e\u5e93\u540d', max_length=100, unique=True)),
                ('comment', models.CharField(blank=True, help_text='\u6ce8\u91ca', max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u7d22\u5f15\u540d', max_length=100)),
                ('type', models.CharField(help_text='\u7c7b\u578b', max_length=100)),
                ('include_columns', models.CharField(blank=True, help_text='\u5305\u542b\u5b57\u6bb5', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u8868\u540d', max_length=100)),
                ('comment', models.CharField(blank=True, help_text='\u6ce8\u91ca', max_length=5000, null=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Database')),
            ],
        ),
        migrations.AddField(
            model_name='index',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Table'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Table'),
        ),
    ]
