# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20180802_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='config',
            field=models.CharField(default=1, help_text='\u914d\u7f6e', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='charset',
            field=models.CharField(blank=True, help_text='\u7f16\u7801', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='engine',
            field=models.CharField(blank=True, help_text='\u5f15\u64ce', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='charset',
            field=models.CharField(blank=True, help_text='\u7f16\u7801', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='engine',
            field=models.CharField(blank=True, help_text='\u5f15\u64ce', max_length=10, null=True),
        ),
    ]
