# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_auto_20180803_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='is_null',
            field=models.NullBooleanField(choices=[(True, 'NULL'), (False, 'NOT NULL')], help_text='\u53ef\u7a7a'),
        ),
        migrations.AlterField(
            model_name='database',
            name='config',
            field=models.CharField(help_text='\u914d\u7f6e', max_length=1000, unique=True),
        ),
    ]
