# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0007_auto_20180807_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='charset',
            field=models.CharField(blank=True, default='utf8', help_text='\u7f16\u7801', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='comment',
            field=models.CharField(blank=True, default='TBD', help_text='\u6ce8\u91ca', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='engine',
            field=models.CharField(blank=True, default='InnoDB', help_text='\u5f15\u64ce', max_length=10, null=True),
        ),
    ]
