# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0011_auto_20180914_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='config',
            field=models.CharField(help_text='\u914d\u7f6e', max_length=1000, unique=True),
        ),
    ]
