# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0012_auto_20180925_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='column',
            name='is_enum',
            field=models.BooleanField(default=False),
        ),
    ]
