# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-16 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0013_auto_20181016_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_comment_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
