# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-10 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0014_column_is_comment_dirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='enable',
            field=models.NullBooleanField(choices=[(True, 'on'), (False, 'off')], default=True, help_text='\u662f\u5426\u542f\u7528'),
        ),
    ]
