# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0015_auto_20181210_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
