# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-22 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0016_table_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='other_enums',
            field=models.CharField(blank=True, help_text='\u672a\u5339\u914d\u7684\u679a\u4e3e\u503c', max_length=100, null=True),
        ),
    ]
