# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-24 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0018_auto_20190422_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='other_enums',
            field=models.TextField(blank=True, default='', help_text='\u672a\u5339\u914d\u7684\u679a\u4e3e\u503c', max_length=2000, null=True),
        ),
    ]
